/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'STUERGU' at '23/05/16 10:55' with Gradle 2.9
 *
 * @author STUERGU, @date 23/05/16 10:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
